LangString addOrReinstall ${LANG_FRENCH} "Réparer NetsuCast (recommandé)"
LangString alreadyInstalled ${LANG_FRENCH} "NetsuCast est déjà installé"
LangString alreadyInstalledLong ${LANG_FRENCH} "Cette version de NetsuCast est déjà présente. Réparer remplace les fichiers de l'application sans supprimer tes réglages."
LangString appRunning ${LANG_FRENCH} "NetsuCast est en cours d'exécution. Ferme l'application puis réessaie."
LangString appRunningOkKill ${LANG_FRENCH} "NetsuCast est en cours d'exécution.$\nClique sur OK pour la fermer."
LangString chooseMaintenanceOption ${LANG_FRENCH} "Choisis l'action à effectuer."
LangString choowHowToInstall ${LANG_FRENCH} "Une version de NetsuCast est déjà installée. Choisis l'action à effectuer."
LangString createDesktop ${LANG_FRENCH} "Créer un raccourci sur le bureau"
LangString dontUninstall ${LANG_FRENCH} "Mettre à jour sans désinstaller (recommandé)"
LangString dontUninstallDowngrade ${LANG_FRENCH} "Conserver la version actuelle (le retour en arrière sans désinstallation est désactivé)"
LangString failedToKillApp ${LANG_FRENCH} "NetsuCast n'a pas pu être fermé. Ferme-le manuellement puis réessaie."
LangString installingWebview2 ${LANG_FRENCH} "Installation de WebView2…"
LangString newerVersionInstalled ${LANG_FRENCH} "Une version plus récente de NetsuCast est déjà installée. Choisis l'action puis clique sur Suivant."
LangString older ${LANG_FRENCH} "ancienne"
LangString olderOrUnknownVersionInstalled ${LANG_FRENCH} "NetsuCast $R4 est déjà installé. La mise à jour conserve tes données ; la réparation remplace seulement les fichiers de l'application."
LangString silentDowngrades ${LANG_FRENCH} "Le retour vers une version antérieure est désactivé pour l'installation silencieuse.$\n"
LangString unableToUninstall ${LANG_FRENCH} "Impossible de désinstaller NetsuCast."
LangString uninstallApp ${LANG_FRENCH} "Désinstaller NetsuCast"
LangString uninstallBeforeInstalling ${LANG_FRENCH} "Désinstaller puis installer"
LangString unknown ${LANG_FRENCH} "inconnue"
LangString webview2AbortError ${LANG_FRENCH} "L'installation de WebView2 a échoué. NetsuCast nécessite WebView2 pour fonctionner."
LangString webview2DownloadError ${LANG_FRENCH} "Erreur lors du téléchargement de WebView2 : $0"
LangString webview2DownloadSuccess ${LANG_FRENCH} "WebView2 a été téléchargé."
LangString webview2Downloading ${LANG_FRENCH} "Téléchargement de WebView2…"
LangString webview2InstallError ${LANG_FRENCH} "L'installation de WebView2 a échoué (code $1)."
LangString webview2InstallSuccess ${LANG_FRENCH} "WebView2 est installé."
LangString deleteAppData ${LANG_FRENCH} "Supprimer les données de l'application"
