LangString addOrReinstall ${LANG_ENGLISH} "Repair NetsuCast (recommended)"
LangString alreadyInstalled ${LANG_ENGLISH} "NetsuCast is already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "This version of NetsuCast is already installed. Repair replaces application files without deleting your settings."
LangString appRunning ${LANG_ENGLISH} "NetsuCast is running. Close the application and try again."
LangString appRunningOkKill ${LANG_ENGLISH} "NetsuCast is running.$\nClick OK to close it."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose the action to perform."
LangString choowHowToInstall ${LANG_ENGLISH} "A version of NetsuCast is already installed. Choose the action to perform."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Update without uninstalling (recommended)"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Keep the current version (downgrading without uninstalling is disabled)"
LangString failedToKillApp ${LANG_ENGLISH} "NetsuCast could not be closed. Close it manually and try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2…"
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of NetsuCast is already installed. Choose the action you want, then click Next."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "NetsuCast $R4 is already installed. Updating keeps your data; repair replaces application files only."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrading is disabled for silent installation.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall NetsuCast."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall NetsuCast"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall and install"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 installation failed. NetsuCast requires WebView2 to run."
LangString webview2DownloadError ${LANG_ENGLISH} "WebView2 download failed: $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 was downloaded."
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2…"
LangString webview2InstallError ${LANG_ENGLISH} "WebView2 installation failed (code $1)."
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 is installed."
LangString deleteAppData ${LANG_ENGLISH} "Delete application data"
